name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint with mypy
              run: pip install mypy &&
                mypy .

            - name: Lint with flake8
              run: pip install flake8 flake8-html &&
                flake8 --format=html --htmldir=flake-report

    send_notification:
        needs: [ lint ]
        runs-on: ubuntu-latest
        steps:
            - name: Send Telegram notification
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: |
                  ${{ github.actor }} created commit:
                  Commit message: ${{ github.event.commits[0].message }}
                  
                  Repository: ${{ github.repository }}
                  
                  See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}